### ISSUE TITLE
This channel is not responding

### ISSUE THREAD

**Issue by kalmondo** [Twoure/KissNetwork.bundle#3] opened 2015-12-13 16:46 UTC
I keep getting the error message "This channel is not responding" when loading search or any letter under alphabets. I installed the master one that was listed in the read me after the link in the main page failed to show up under the channels list. I am running win 10, also got errors when trying to pull up content on plex app on Roku 3. I do not know where the error logs are saved, so alas, I have no log for you.

**Comment by Twoure** [comment] 2015-12-13 17:43
Log files can be found here: https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files
Need `com.plexapp.plugins.kissnetwork.log` and `com.plexapp.system.log` to get an idea of what is going on.

**Comment by michaelonjack** [comment] 2016-01-08 10:41
I'm having the same issue. I'm able to watch a few episodes but after awhile I continually get the "This channel is not responding" message.

this is the output of com.plexapp.plugins.kissnetwork.log 

[com.plexapp.plugins.kissnetwork.txt](https://github.com/Twoure/KissNetwork.bundle/files/82550/com.plexapp.plugins.kissnetwork.txt)

this is the output of com.plexapp.system.log

[com.plexapp.system.txt](https://github.com/Twoure/KissNetwork.bundle/files/82541/com.plexapp.system.txt)

**Comment by Twoure** [comment] 2016-01-09 02:01
@michaelonjack If you use the cache all image settings, then you run the possibility of hitting the upper limit for your IP to access the domain.  This can also happen when the the _cache all images_ is turned on and you continue to hit the next button on a directory list that has to pull down fresh images.  Usually this can be remedied by waiting until your IP is allowed access.  Think it is around an hour wait time, maybe more don't remember right now.

Some other test:
- can you access the sites directly from your computer running PMS? If not then your IP may be banned, as I described above
- If you can access the websites directly, then try a different client.  Might be a client cache error (most likely not in your case)

I'll boot up my Windows machine and do some testing to see if I can reproduce your error.

Keep me posted,
Twoure

**Comment by michaelonjack** [comment] 2016-01-09 03:52
@Twoure thanks for the response! Both "Cache All Covers Locally" and "Cache Bookmark Covers Locally" were unselected and I am able to access both KissAnime and KissCartoon on my machine. Any other potential ideas?

If I delete the Dict and Header_Dict files and redownload the KissNetwork.bundle, the channel begins to work again but after watching a few episodes I start to get the same error

**Comment by Twoure** [comment] 2016-01-09 05:38
@michaelonjack Hmm, that's interesting.  It would suggest an error in the cookies cache time.  Please reset the channel and reproduce the error, then post the logs again.  Just to clarify, you are using the _master_ branch correct?

**Comment by Twoure** [comment] 2016-02-11 05:53
@kalmondo and @michaelonjack since I have not heard from either of you, I am assuming your issues were resolved?  Please let me know within the next couple of days, after that I'm closing this issue.  You can always open another issue for resolution or head over to the forums to get help https://forums.plex.tv/discussion/186988.

**Comment by Twoure** [comment] 2016-02-21 02:20
Close issue since users are not responding.  Please open another issue if you have one.

**Closed as completed by Twoure** 2016-02-21 02:20 UTC
